name: seevio
description: A new Flutter project.

publish_to: 'none' # Do not remove pls
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  http: ^0.12.1
  geolocator: ^5.3.2+2
  flutter_tts: ^1.3.0 
  shared_preferences: 0.5.12+4 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: LibreFrankin
      fonts: 
        - asset: assets/LibreFranklin-Bold.ttf
        - asset: assets/LibreFranklin-Light.ttf
        - asset: assets/LibreFranklin-Medium.ttf
